<a href="https://colab.research.google.com/github/PollyIva/NLP-projects/blob/main/NLP_Hate_speech.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
#pip install scikit-learn
#import sklearn
from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
#import xgboost as xgb

from sklearn import metrics

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
#df = pd.read_csv('train.csv')
df = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/NPL_with_tutor/Hate_speech/train.csv')

In [4]:
df

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
0           0             0        0       0       0              0  
1           0             0        0       0       0              0  
2           0             0        0       0       0              0  
3           0             0        0       0       0              0  
4           0             0        0       0       0              0  
...       ...           ...      ...     ...     ...            ...  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0  

[159571 rows x 8 columns]

In [5]:
df.isna().sum()

id               0
comment_text     0
toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
dtype: int64

In [6]:
colums = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

In [7]:
df['score']=df[colums].sum(axis=1)

In [8]:
df

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  score  
0           0             0        0       0       0              0      0  
1           0             0        0       0       0              0      0  
2           0             0        0       0       0              0      0  
3           0             0        0       0       0              0      0  
4           0             0        0       0       0              0      0  
...       ...           ...      ...     ...     ...            ...    ...  
159566      0             0        0       0       0              0      0  
159567      0             0        0       0       0              0      0  
159568      0             0        0       0       0              0      0  
159569      0             0        0       0       0              0      0  
159570      0             0        0       0       0              0      0  

[159571 rows x 9 columns]

In [9]:
df.score.value_counts()

0    143346
1      6360
3      4209
2      3480
4      1760
5       385
6        31
Name: score, dtype: int64

In [10]:
df = df.drop(colums, axis =1)

In [11]:
df

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        score  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
159566      0  
159567      0  
159568      0  
159569      0  
159570      0  

[159571 rows x 3 columns]

In [12]:
df.score.value_counts()

0    143346
1      6360
3      4209
2      3480
4      1760
5       385
6        31
Name: score, dtype: int64

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

# Fit and transform the data
scaled_data = scaler.fit_transform(df['score'].values.reshape(-1, 1))

In [14]:
df['score'] = scaled_data

In [15]:
df['score']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
159566    0.0
159567    0.0
159568    0.0
159569    0.0
159570    0.0
Name: score, Length: 159571, dtype: float64

In [16]:
df[df['score']!=0.0]

id                                       comment_text  \
6       0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
12      0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
16      0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
42      001810bf8c45bf5f  You are gay or antisemmitian? \n\nArchangel WH...   
43      00190820581d90ce           FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!   
...                  ...                                                ...   
159494  fef4cf7ba0012866  "\n\n our previous conversation \n\nyou fuckin...   
159514  ff39a2895fc3b40e                  YOU ARE A MISCHIEVIOUS PUBIC HAIR   
159541  ffa33d3122b599d6  Your absurd edits \n\nYour absurd edits on gre...   
159546  ffb47123b2d82762  "\n\nHey listen don't you ever!!!! Delete my e...   
159554  ffbdbb0483ed0841  and i'm going to keep posting the stuff u dele...   

           score  
6       0.666667  
12      0.166667  
16      0.166667  
42      0.666667  
43      0.500000  
...          ...  
159494  0.666667  
159514  0.333333  
159541  0.500000  
159546  0.333333  
159554  0.500000  

[16225 rows x 3 columns]

In [17]:
df = df.drop('id', axis = 1)

In [18]:
df

comment_text  score
0       Explanation\nWhy the edits made under my usern...    0.0
1       D'aww! He matches this background colour I'm s...    0.0
2       Hey man, I'm really not trying to edit war. It...    0.0
3       "\nMore\nI can't make any real suggestions on ...    0.0
4       You, sir, are my hero. Any chance you remember...    0.0
...                                                   ...    ...
159566  ":::::And for the second time of asking, when ...    0.0
159567  You should be ashamed of yourself \n\nThat is ...    0.0
159568  Spitzer \n\nUmm, theres no actual article for ...    0.0
159569  And it looks like it was actually you who put ...    0.0
159570  "\nAnd ... I really don't think you understand...    0.0

[159571 rows x 2 columns]

In [19]:
import spacy
nlp = spacy.load("en_core_web_sm")
import re
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords = stopwords.words("english")

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [20]:
from nltk.stem import LancasterStemmer
lancaster=LancasterStemmer()

In [21]:
lancaster=LancasterStemmer()
def normalization_text(x):
    sentences = nltk.sent_tokenize(x)
    words = [nltk.word_tokenize(sentence) for sentence in sentences]
    bag_of_text = []
    for sent in words:
        sentense = [lancaster.stem(word.lower()).strip() for word in sent if not word.lower() in stopwords and word.isalpha()]
        if len(sentense) > 0:
            bag_of_text.extend(sentense)

    bag_of_text = " ".join(bag_of_text)
    return bag_of_text

In [22]:
df['comment_text'] = df['comment_text'].apply(lambda x: normalization_text(x))
df

comment_text  score
0       expl edit mad usernam hardc metallic fan rever...    0.0
1       match background colo seem stuck thank talk ja...    0.0
2       hey man real try edit war guy const remov rele...    0.0
3       ca mak real suggest improv wond sect stat lat ...    0.0
4                               sir hero chant rememb pag    0.0
...                                                   ...    ...
159566  second tim ask view complet contradict cov rel...    0.0
159567                      asham horr thing put talk pag    0.0
159568  spitz um ther act artic prostitut ring crunch ...    0.0
159569      look lik act put speedy first vert delet look    0.0
159570  real think understand cam ide bad right away k...    0.0

[159571 rows x 2 columns]

In [23]:
df['comment_text'][1]

'match background colo seem stuck thank talk janu utc'

In [24]:
len(df['comment_text'][1])

52

In [25]:
X_train, X_test, y_train, y_test = train_test_split(df['comment_text'], df['score'], test_size=0.33, random_state=42)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train) # remember to use the original X_train set
#X_test_tfidf = vectorizer.fit_transform(df['comment_text'])

In [27]:
print(X_train_tfidf[0])

  (0, 20510)	0.09630934401618203
  (0, 68077)	0.22204472510191609
  (0, 49033)	0.12224238605898949
  (0, 23286)	0.22322565839034747
  (0, 67992)	0.15010507638949397
  (0, 41964)	0.23372221034801077
  (0, 22546)	0.3540052105955278
  (0, 12303)	0.40035257405549207
  (0, 16708)	0.22889743346645589
  (0, 64947)	0.22418632308264852
  (0, 77759)	0.10132242715079717
  (0, 57998)	0.13762808685934047
  (0, 53993)	0.21153239205097352
  (0, 482)	0.18749505305168368
  (0, 11035)	0.15276195997719208
  (0, 64950)	0.5280061034533762


In [28]:
print(X_train.iloc[0])

sockpuppetry cas accus sockpuppetry pleas ref wikiped sockpuppet de chinelo evid pleas mak sur mak famili not suspect edit evid


In [29]:
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
#define model
model = XGBRegressor()
#bundle preprocessing and modelling code in pipeline
my_pipeline = Pipeline(steps=[('TFiDF',TfidfVectorizer()),
                              ('model',model)])
#preprocessinf of training data, fit model
my_pipeline.fit(X_train, y_train)
#preprocessing of validation data, get predictions
xgb_preds = my_pipeline.predict(X_test)

[20:12:15] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [30]:
score = my_pipeline.score(X_test, y_test) # Return the coefficient of determination of the prediction.R^2
print("Training score: ", score)

Training score:  0.6331584064279642


In [31]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, xgb_preds)
print('mse ----> ', mse)

mse ---->  0.005749913742498156


In [ ]:
def test_model(comment_test):
    df_test = pd.DataFrame(comment_test, columns=['comment_test'])
    df_test['comment_test'] = df_test['comment_test'].apply(lambda x:normalization_text(x))
    predict = my_pipeline.predict(df_test['comment_test'])
    return predict

In [ ]:
comment_test = ['Fuck of and shut up kiss my ass!']
predict = test_model(comment_test)
predict

array([0.51662093], dtype=float32)

#TensorFlow

In [29]:
import tensorflow
import keras
from keras.layers import Dense
from keras.models import Sequential
from keras.optimizers import Adam 
from keras.callbacks import EarlyStopping
from keras.utils import np_utils
from keras.layers import LSTM
from keras.layers import Embedding

In [30]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [31]:
# vectorizer = TfidfVectorizer()

# X_train_tfidf = vectorizer.fit_transform(X_train) # remember to use the original X_train set
# X_test_tfidf = vectorizer.fit_transform(X_test)
from tensorflow.keras.preprocessing.text import Tokenizer
oov_token = '<UNK>'

tokenizer = Tokenizer(num_words=100, oov_token=oov_token)
tokenizer.fit_on_texts(X_train)

In [32]:
word_index = tokenizer.word_index

In [33]:
train_sequences = tokenizer.texts_to_sequences(X_train)
train_sequences

[[1, 1, 1, 1, 11, 46, 6, 1, 1, 1, 1, 11, 18, 1, 18, 1, 16, 1, 5, 1],
 [48, 1, 1, 1, 1, 4, 1, 26, 18, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [6, 1, 1, 1, 1, 1, 1, 68, 2, 1, 1, 1, 1, 18, 2, 1],
 [95, 1, 1, 1, 1, 1, 95, 1, 1, 1, 1, 1, 1, 1, 1, 73, 1, 1, 1, 1, 25],
 [1,
  1,
  1,
  97,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  67,
  1,
  1,
  1,
  1,
  1,
  77,
  9,
  18,
  1,
  1,
  61,
  1,
  11,
  98,
  22,
  72,
  1,
  1,
  14],
 [8,
  28,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  8,
  53,
  1,
  30,
  62,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  79,
  1,
  1,
  79,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  17,
  1,
  1,
  1,
  26,
  1,
  1,
  1,
  79,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  20,
  35,
  47,
  1,
  35,
  1,
  25,
  1,
  1,
  1,
  1,
  1,
  1,
  23,
  1,
  30,
  1,
  17,
  1,
  9,
  1,
  1,
  1,
  1,
  1,
  1],
 [2, 1, 1, 1, 1, 1, 1, 46],
 [1, 1, 1, 1, 68, 49, 80, 1, 46, 60, 1, 1, 1, 20, 1, 1, 1, 1, 1, 1, 1],
 [58, 60, 1, 1, 5, 4, 1, 1, 1, 1, 31, 1],
 [5,
  11,
  63,
  1,
  

In [34]:
maxlen = max([len(x) for x in train_sequences])

In [35]:
len(word_index)

82334

In [36]:
training_padded = pad_sequences(train_sequences,
                                maxlen=maxlen, 
                                truncating='post', 
                                padding='post'
                               )

test

In [37]:
test_sequences = tokenizer.texts_to_sequences(X_test)

testting_padded = pad_sequences(test_sequences,
                                maxlen=maxlen, 
                                truncating='post', 
                                padding='post'
                               )

In [38]:
testting_padded[0]

array([1, 1, 1, ..., 0, 0, 0], dtype=int32)

In [39]:
vocab_size = len(word_index)

In [40]:
model = Sequential()
model.add(Embedding(vocab_size, 128, input_length=maxlen)) #why 128 -> 512
model.add(LSTM(512, dropout=0.2, recurrent_dropout=0.2, return_sequences=True))
model.add(LSTM(128, dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(16, activation='relu'))
model.add(Dense(1))



model.compile(
    loss= tensorflow.keras.metrics.mean_squared_error,
    optimizer='Adam',
    metrics=[tensorflow.keras.metrics.RootMeanSquaredError(name='rmse')])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1250, 128)         10538752  
                                                                 
 lstm (LSTM)                 (None, 1250, 512)         1312768   
                                                                 
 lstm_1 (LSTM)               (None, 128)               328192    
                                                                 
 dense (Dense)               (None, 16)                2064      
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 12,181,793
Trainable params: 12,181,793
Non-trainable params: 0
_________________________________________________________________


In [ ]:
history = model.fit(training_padded, y_train, epochs = 1, batch_size=128)

In [ ]:
model.save("/content/drive/MyDrive/Colab_Notebooks/NPL_with_tutor/Hate_speech/model")

In [38]:
loaded_model = keras.models.load_model('/content/drive/MyDrive/Colab_Notebooks/NPL_with_tutor/Hate_speech/model')

In [39]:
test_padded = pad_sequences(X_test_tfidf.toarray(),
                                maxlen=50, 
                                truncating='post', 
                                padding='post'
                               )

In [43]:
test_padded[:10]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [44]:
y_pred = loaded_model.predict(test_padded[:10])

1/1 [==============================] - 0s 150ms/step


In [45]:
y_pred

array([[0.03216351],
       [0.03216351],
       [0.03216351],
       [0.03216351],
       [0.03216351],
       [0.03216351],
       [0.03216351],
       [0.03216351],
       [0.03216351],
       [0.03216351]], dtype=float32)